FROM node:latest

RUN npm install -g bower
RUN npm install -g gulp
RUN npm install gulp

RUN git config --global user.email "leandrolourenci@gmail.com"
RUN git config --global user.name "Leandro Lourenci"
