version: '3'
services:
  db:
    image: postgres:9.6.3-alpine
    ports:
        - "5432:5432"
    environment:
      POSTGRES_DB: rails_ruby
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
  web:
    build:
      context: ./rails-ruby
      args:
        - user=${USER}
    image: rails-ruby
    command: tail -f /dev/null
    links:
      - db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
